swagger: "2.0"
info:
  version: 1.0.0
  title: "trentose2e1"
  description: Practice exam simulation
host: trentose2e1.herokuapp.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  